spring.jpa:
  database: POSTGRESQL
  show-sql: true

spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/estudoCrud
  username: postgres
  password: 123456
