server:
    port: 8092
    servlet:
        context-path: /spring-estudo


spring:
  datasource:
    password: 123456
    username: postgres
    url: jdbc:postgresql://localhost:5432/crud_estudo
  jpa:
    show-sql: true